return {
  "johmsalas/text-case.nvim",
  config = function()
    local builtin = require('textcase')
    vim.keymap.set('v', "<leader>Ku", function()
      builtin.operator('to_upper_case')
    end, { desc = "[C]hange [C]ase to upper case" })
    vim.keymap.set('v', "<leader>Kl", function()
      builtin.operator('to_lower_case')
    end, { desc = "[C]hange [C]ase to lower case" })
    vim.keymap.set('v', "<leader>Ks", function()
      builtin.operator('to_snake_case')
    end, { desc = "[C]hange [C]ase to snake case" })
    vim.keymap.set('v', "<leader>Kd", function()
      builtin.operator('to_dash_case')
    end, { desc = "[C]hange [C]ase to dash case" })
    vim.keymap.set('v', "<leader>Kn", function()
      builtin.operator('to_constant_case')
    end, { desc = "[C]hange [C]ase to constant case" })
    vim.keymap.set('v', "<leader>Kd", function()
      builtin.operator('to_dot_case')
    end, { desc = "[C]hange [C]ase to dot case" })
    vim.keymap.set('v', "<leader>Ka", function()
      builtin.operator('to_phrase_case')
    end, { desc = "[C]hange [C]ase to phrase case" })
    vim.keymap.set('v', "<leader>Kc", function()
      builtin.operator('to_camel_case')
    end, { desc = "[C]hange [C]ase to camel case" })
    vim.keymap.set('v', "<leader>Kp", function()
      builtin.operator('to_pascal_case')
    end, { desc = "[C]hange [C]ase to pascal case" })
    vim.keymap.set('v', "<leader>Kt", function()
      builtin.operator('to_title_case')
    end, { desc = "[C]hange [C]ase to title case" })
    vim.keymap.set('v', "<leader>Kf", function()
      builtin.operator('to_path_case')
    end, { desc = "[C]hange [C]ase to path case" })
  end
}
